name: Sanitizers

on:
  pull_request:
    branches: [main]
  
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_sanitizers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        id: install_deps
        run: |
         
          sudo scripts/install_deps_ubuntu.sh 

      - name: Build
        id: run_cmake
        run: ls -l

